One_Way_Anova_CBSE <- read_excel("C:/Users/pranj/Desktop/data_analytics/One_Way_Anova_ CBSE.xlsx")
attach(One_Way_Anova_CBSE)
str(One_Way_Anova_CBSE)
One_Way_Anova_CBSE$Category<-as.factor(One_Way_Anova_CBSE$Category)
str(One_Way_Anova_CBSE)
library(car)
leveneTest(Marks~Category, data = One_Way_Anova_CBSE)
#one way ANOVA test
model<-aov(Marks~Category,data=One_Way_Anova_CBSE)
summary(model)
TukeyHSD(model)
model.tables(model,"mean")
model$residuals
shapiro.test(model$residuals)
library(nortest)
lillie.test(model$residuals)
ad.test(model$residuals)
library(moments)
skewness(`model$residuals`)
